Dependency Bumps and Apache httpclient5 migration
Azure/azure-kusto-java pull request #251
Opened 2022-06-16 18:15 UTC by The-Funk

#### Pull Request Description

-updated all dependencies to latest
-migrated apache httpclient to version 5

---

#### Future Release Comment
This upgrades the version of the Apache httpclient used by the library to version 5 for incoming support of asynchronous/non-blocking ADX queries.

**Breaking Changes:**
There are 2 test failures total.

1. createExceptionFromBlankErrorMessage() in UtilitiesTest in kusto-data module
2. E2ETest in kusto-ingest

There is a TODO in the code for the max connections parameter. It does not appear that version 5 of the Apache http client supports a max connections parameter.

**Features:**
Everything is up to date and new Apache client appears to work

**Fixes:**
NA

2022-06-20 10:44 UTC, ohadbitt requested changes
This simply doesnt work now with trying to execute simple commands ( tried to create a table)
The returned response is not a json

2022-06-20 10:44 UTC, ohadbitt commented on pom.xml
> +        <azure-core.version>1.29.1</azure-core.version>
Please don't touch azure core versions

2022-06-23 04:40 UTC, ohadbitt commented
doesn't seem like you changed something to make it work - please try to invoke any command using this

2022-06-26 09:37 UTC, ohadbitt commented
> I'll give it a go. How do you want me to run tests? I've just been doing mvn test and everything appears okay with that minus the two tests I listed above. You want me to build a jar, import it in a project, connect it to my own ADX instance and then manually test?
> 
> I noticed a similar JSON issue in 3.1.2. For some reason JSON isn't working properly for me in that version. However, 3.1.1 works fine.

All tests should pass
If e2e passes thats fine with fixing what i said.

2022-06-28 08:14 UTC, AsafMah commented on data/src/main/java/com/microsoft/azure/kusto/data/Utils.java
>              }
```
 try (CloseableHttpResponse response = httpClient.execute(request)) {
                if (response != null) {
                    String responseContent = EntityUtils.toString(response.getEntity());

                    switch (response.getCode()) {
                        case HttpStatus.SC_OK:
                            return responseContent;
                        case HttpStatus.SC_TOO_MANY_REQUESTS:
                            throw new ThrottleException(urlStr);
                        default:
                            throw createExceptionFromResponse(urlStr, response, null, responseContent);
                    }
                }
            }
```


You need to use Entity to get the actual content of the response, response.toString() just gives the status line.

Fix this and the tests will pass.

2022-06-28 13:02 UTC, The-Funk commented
Oh my goodness. I can't believe I forgot to change that back. I added response.getEntity().toString(), if you'd like to use EntityUtils to do that conversion I can switch back to EntityUtils.

2022-06-28 14:32 UTC, AsafMah commented
@The-Funk still doesn't work for me, entity.toString() gives me "Wrapper [Wrapper [[Content-Type: application/json; charset=UTF-8,Content-Encoding: gzip,Chunked: true]]]"

You can just use the code I gave.

Also please resolve the merge conflicts if you can.

2022-06-29 12:08 UTC, The-Funk commented
> @The-Funk still doesn't work for me, entity.toString() gives me "Wrapper [Wrapper [[Content-Type: application/json; charset=UTF-8,Content-Encoding: gzip,Chunked: true]]]"
> 
> You can just use the code I gave.
> 
> Also please resolve the merge conflicts if you can.

Sounds good. I'll try to work on this today, sorry for the delay.

2022-06-29 19:34 UTC, The-Funk commented
@AsafMah a lot on the go today so I might have rushed those merge conflict fixes. Hopefully third time is the charm. Haven't tried E2ETest yet.

2022-06-29 19:47 UTC, The-Funk commented
Nevermind, I think I accidentally kept your changes and deleted mine. Not my day. :(

2022-07-03 06:57 UTC, AsafMah commented
There seemed to be some merge complications,
So I re-did it myself, and solved the todos/fixme.

The PR is now in #257, so I'm closing this one.

2022-07-03 06:57 UTC, closed without merging