Dont use timer if closed
Azure/azure-kusto-java pull request #312
Opened 2023-07-23 12:05 UTC by ohadbitt

2023-07-23 15:26 UTC, yogilad commented
Can you please add a description?
This is also so the change list for the version can be easily composed

2023-07-23 15:27 UTC, yogilad approved these changes

2023-07-24 05:56 UTC, AsafMah approved these changes

2023-07-24 07:21 UTC, AsafMah requested changes
Add to changelog.md

2023-07-24 07:36 UTC, ohadbitt commented
> This is also so the change list for the version c

The description wouldve been a copy of the title

2023-07-25 22:29 UTC, AsafMah commented on data/src/main/java/com/microsoft/azure/kusto/data/auth/PublicAppTokenProviderBase.java
> +    protected synchronized String acquireAccessTokenImpl() throws DataServiceException, DataClientException {
Add a comment explaining this.

2023-07-25 22:30 UTC, AsafMah approved these changes
Approved - just add the comment, and make sure it actually does what it should (not making the thing pop up twice)

2023-07-26 14:35 UTC, merged